services:
  sound-api-service:
    build:
        context: .
        dockerfile: ./TaskManagement.Api/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty12345
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    ports:
    - 5000:443
    - 5001:80
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TaskManagement