services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5111:5432
    container_name: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TaskManagement

  api:
    build:
        context: .
        dockerfile: ./TaskManagement.Api/Dockerfile
    container_name: api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty12345
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres

    ports:
    - 5000:443
    - 5001:80